decoder_dim: 512
decoder_num_heads: 8
decoder_num_layers: 8
encoder_depth: 40
encoder_embed_dim: 1408
encoder_num_heads: 16
img_size: 256
lambda_2d: 0.1
lambda_3d: 1.0
lambda_confidence: 0.2
lambda_motion: 0.1
lambda_normal: 0.5
lambda_visibility: 0.1
lr: 0.0001
max_epochs: 100
max_frames: 100
max_steps: 500000
patch_size: 16
warmup_steps: 2500
weight_decay: 0.03
